[package]
description = "nodejs resolve"
edition = "2021"
license = "MIT"
name = "nodejs-resolver"
repository = "https://github.com/bvanjoi/nodejs_resolver"
version = "0.0.40"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daachorse = "1.0.0"
dashmap = "5.4.0"
futures = "0.3.24"
indexmap = "1.9.1"
jsonc-parser = {version = "0.21.0", features = ["serde"]}
once_cell = "1.14.0"
serde = {version = "1.0.144", features = ["derive"]}
serde_json = {version = "1.0.85", features = ["preserve_order"]}
smol_str = "0.1.23"
tracing = "0.1.36"

[dev-dependencies]
tracing-span-tree = "0.1.1"
tracing-subscriber = "0.3.15"

[profile.bench]
lto = true

[profile.release]
lto = true
